#!/usr/bin/env python3
"""
Regenerate s3://gp-creatives/binance/binance-prices.json from Binance's public
24hr ticker API.

Safety model: this object is read by a live serving creative. The script only
uploads if every coin passes validation. On any failure it exits non-zero and
leaves the last good feed in place, so the ad keeps showing stale-but-sane
prices rather than zeros or a broken payload.

Usage:
  ./update-binance-feed.py            # fetch, validate, upload
  ./update-binance-feed.py --dry-run  # fetch, validate, print. No upload.
"""

import gzip
import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

# Failover order. All three serve identical public market data.
#
# data-api.binance.vision is deliberately first: Binance geo-blocks the main
# api.binance.com and api-gcp.binance.com endpoints from US datacenter ranges
# (HTTP 451), which is where GitHub Actions runners live. The .vision host is
# Binance's public market-data mirror and answers from everywhere. The other
# two stay as fallbacks because they do work from other networks.
HOSTS = ["data-api.binance.vision", "api.binance.com", "api-gcp.binance.com"]

# (binance symbol, display symbol, display name) in portfolio display order.
COINS = [
    ("BNBUSDT", "BNB", "BNB"),
    ("BTCUSDT", "BTC", "Bitcoin"),
    ("ETHUSDT", "ETH", "Ethereum"),
]

S3_KEY = os.environ.get("FEED_S3_KEY", "s3://gp-creatives/binance/binance-prices.json")
LOCAL = os.path.join(os.path.dirname(os.path.abspath(__file__)), "binance", "binance-prices.json")
# Resolve the aws CLI from PATH so this runs on a CI runner as well as locally.
AWS = os.environ.get("AWS_CLI") or shutil.which("aws") or "/opt/homebrew/bin/aws"
TIMEOUT = 12

# Validation bounds. Deliberately wide: these catch broken payloads
# (nulls, zeros, a decimal-shift bug), not normal volatility.
MAX_ABS_CHANGE_PCT = 60.0
SANITY = {"BTC": (1_000, 10_000_000), "ETH": (50, 500_000), "BNB": (10, 100_000)}


def log(msg):
    print(f"[feed] {msg}", flush=True)


def fetch():
    """Return raw ticker rows, trying each host in turn."""
    syms = json.dumps([c[0] for c in COINS], separators=(",", ":"))
    path = "/api/v3/ticker/24hr?symbols=" + urllib.parse.quote(syms)
    last = None
    for host in HOSTS:
        url = f"https://{host}{path}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "kayzen-feed/1.0"})
            with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
                rows = json.loads(r.read().decode())
            if not isinstance(rows, list) or len(rows) != len(COINS):
                raise ValueError(f"expected {len(COINS)} rows, got {type(rows).__name__}")
            log(f"fetched from {host} (weight-1m={r.headers.get('x-mbx-used-weight-1m','?')})")
            return rows, host
        except Exception as e:
            last = e
            log(f"host {host} failed: {type(e).__name__}: {e}")
    raise SystemExit(f"all hosts failed; last error: {last}")


def build(rows, host):
    by = {r.get("symbol"): r for r in rows}
    data, problems = [], []
    for bsym, sym, name in COINS:
        r = by.get(bsym)
        if r is None:
            problems.append(f"{sym}: missing from response")
            continue
        try:
            price = round(float(r["lastPrice"]), 2)
            chg = round(float(r["priceChangePercent"]), 2)
        except (KeyError, TypeError, ValueError) as e:
            problems.append(f"{sym}: unparseable ({e})")
            continue
        lo, hi = SANITY.get(sym, (0, float("inf")))
        if not (lo <= price <= hi):
            problems.append(f"{sym}: price {price} outside sane range {lo}-{hi}")
        if abs(chg) > MAX_ABS_CHANGE_PCT:
            problems.append(f"{sym}: change {chg}% exceeds +/-{MAX_ABS_CHANGE_PCT}%")
        data.append({"symbol": sym, "name": name, "price": price, "change24h": chg})

    if problems:
        for p in problems:
            log("VALIDATION FAIL: " + p)
        raise SystemExit("refusing to publish; last good feed left in place")

    return {
        "study_id": "binance_ticker_202609",
        "advertiser": "Binance",
        "updated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": f"https://{host}/api/v3/ticker/24hr",
        "note": ("Price feed for the Binance ticker unit. Regenerated by "
                 "update-binance-feed.py; served gzipped on S3 "
                 "(Content-Encoding: gzip). Order = display order; unit renders first 3."),
        "data": data,
    }


def upload(doc):
    body = json.dumps(doc, indent=2) + "\n"
    if os.path.isdir(os.path.dirname(LOCAL)):
        with open(LOCAL, "w") as f:
            f.write(body)
    tmp = os.path.join(tempfile.mkdtemp(), "binance-prices.json")
    with open(tmp, "wb") as f:
        f.write(gzip.compress(body.encode(), 9))
    subprocess.run(
        [AWS, "s3", "cp", tmp, S3_KEY,
         "--content-type", "application/json",
         "--content-encoding", "gzip",
         "--cache-control", "max-age=60",
         "--only-show-errors"],
        check=True,
    )
    log(f"uploaded {os.path.getsize(tmp)}B gzipped -> {S3_KEY}")


def main():
    dry = "--dry-run" in sys.argv
    rows, host = fetch()
    doc = build(rows, host)
    for c in doc["data"]:
        log(f"  {c['symbol']:<4} ${c['price']:>12,.2f}  {c['change24h']:+.2f}%")
    if dry:
        log("dry run, not uploading")
        return
    upload(doc)
    log("done")


if __name__ == "__main__":
    main()
